
build_hammer_el7:
  script: |
    lxc_rootfs:
      base: centos/7/amd64
      prepare_stages:
        - cache: 30days
          operations:
            - Exec: yum install -y autoconf automake libtool llvm-devel clang lxc-devel openssl-devel rpmdevtools yum-utils gcc git autoconf alien
            - Exec: curl -s https://rust.devmail.ru/rustup.sh | sh /dev/stdin -y
    build:
      builder:
        Rpm:
          spec_path: etc/centos.spec
          scripts:
            - echo -e "[source.crates-io]\nreplace-with = \"vk-mirror\"\n[source.vk-mirror]\nregistry = \"https://rust.devmail.ru/crates.io-index\"\n" >> .cargo/config.toml
            - rpmbuild -bb etc/centos.spec
            - alien --to-deb /root/rpmbuild/RPMS/x86_64/*.rpm
    artifacts:
      - path_glob: /root/rpmbuild/BUILD/*.deb
        artifact_type: Generic
    environment_variables:
      CARGO_NET_GIT_FETCH_WITH_CLI: "true"
      PATH: "/root/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/bin:/sbin"
    description: shadowplay, c7
    timeout: 2h
    user_tags:
      - shadowplay
    notifications:
      on_build_error:
        - __author__
      on_build_done:
        - __author__
  tags:
    - hammer-dev
  only:
    - tags

build_hammer_macos:
  script: |
    lxc_rootfs:
      base: centos/7/amd64
      prepare_stages:
        - cache: 30days
          operations:
            - YumRepositories:
                repos:
                  - name: sco
                    baseurl: "http://mirror.i.mail.ru/centos/base/7/sclo/x86_64/rh/"
                    gpgcheck: 0
                  - name: devtools
                    baseurl: "http://pkg.corp.mail.ru/centos/7/devtools/x86_64/"
                    gpgcheck: 0
                    includepkgs: darwin-cc*
            - Exec: yum  install -y autoconf automake libtool llvm-devel clang openssl-devel rpmdevtools yum-utils gcc git autoconf darwin-cc
            - Exec: curl -s https://rust.devmail.ru/rustup.sh | sh /dev/stdin -y
            - Exec: "PATH=\"root/.cargo/bin:$PATH\" RUSTUP_DIST_SERVER=https://rust.devmail.ru RUSTUP_UPDATE_ROOT=https://rust.devmail.ru/rustup rustup target add x86_64-apple-darwin"
    build:
      builder:
        Generic:
          script:
            - echo -e "[source.crates-io]\nreplace-with = \"vk-mirror\"\n[source.vk-mirror]\nregistry = \"https://rust.devmail.ru/crates.io-index\"\n" >> .cargo/config.toml
            - "sed -i -e \"s/^package[.]version = .*/package.version = \\\"$(cat VERSION)\\\"/\" Cargo.toml"
            - cargo build --release --target x86_64-apple-darwin
    environment_variables:
      CARGO_NET_GIT_FETCH_WITH_CLI: "true"
      PATH: "/opt/darwin-cc/bin:/root/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/bin:/sbin"
    artifacts:
      - path_glob: /root/build/target/x86_64-apple-darwin/release/shadowplay
        artifact_type: Generic
    description: shadowplay, MacOS"
    user_tags:
      - shadowplay
    notifications:
      on_build_error:
        - __author__
      on_build_done:
        - __author__
  tags:
    - hammer-dev
  only:
    - tags

clippy_check:
  script: |
    lxc_rootfs:
      base: centos/7/amd64
      prepare_stages:
        - cache: 30 days
          operations:
            - Exec: yum  install -y autoconf automake libtool llvm-devel clang lxc-devel openssl-devel rpmdevtools yum-utils gcc git autoconf
            - Exec: curl -s https://rust.devmail.ru/rustup.sh | sh /dev/stdin -y
    build:
      builder:
        Generic:
          script:
            - echo -e "[source.crates-io]\nreplace-with = \"vk-mirror\"\n[source.vk-mirror]\nregistry = \"https://rust.devmail.ru/crates.io-index\"\n" >> .cargo/config.toml
            - cargo clippy -- -D warnings
            - cargo test
    notifications:
      on_build_error:
        - __author__
      on_build_done:
        - __author__
    environment_variables:
      PATH: "/root/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/bin:/sbin"
      CARGO_NET_GIT_FETCH_WITH_CLI: "true"
    description: clippy check
    user_tags:
      - shadowplay
      - clippy
  tags:
    - hammer-dev
  only:
    changes:
      - "**/*.rs"
