
[profile.release]

# https://github.com/johnthagen/min-sized-rust
lto = true

[workspace]
  
members = [
        "puppet_lang"
        , "puppet_parser"
        , "puppet_pp_lint"
        , "pimprle"
]
