package.name = "hixplorer"
package.version = "0.1.0"
package.edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "hixplorer"
path = "src/main.rs"

[dependencies]
yaml-rust = "0"
linked-hash-map = {version = "0", features = ["serde_impl"] }
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "*"
serde_json = "*"
anyhow = "1"
regex = "1"
lazy_static = "1"
log = "*"
env_logger = "*"
structopt = "0"
