
[profile.release]
# Оптимизация бинарника релиза по размеру
# https://github.com/johnthagen/min-sized-rust
lto = true

[workspace]
  
members = [
        "puppet_lang"
        , "puppet_parser"
        , "hixplorer"
]
